# Generated by Django 3.1.4 on 2020-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pinpoint_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('creator', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('is_collaborative', models.BooleanField(blank=True, null=True)),
                ('is_preview_allowed', models.BooleanField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('caused_by', models.TextField(blank=True, null=True)),
                ('notif_image', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=128, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('pin_image', models.IntegerField(blank=True, null=True)),
                ('author', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('request_image', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_good', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('for_pin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Maps',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Pins',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
